services:
  tracks:
    build:
      context: .
      target: production
    container_name: tracks
    restart: unless-stopped
    volumes:
      - ./database:/app/database
    ports:
      - 3000:3000
