---
name: Automated tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        db: [sqlite, mysql, postgres]
        exclude:
          - ruby: "3.1"
            db: sqlite
          - ruby: "3.1"
            db: postgres
          - ruby: "3.2"
            db: sqlite
          - ruby: "3.2"
            db: postgres

    steps:
      - uses: actions/checkout@v1
      - run: bash -x script/cibuild ${{ matrix.ruby }} ${{ matrix.db }}
